SPOOL log_temp.txt

PROMPT Модуль экспертной системы
PROMPT Удаляем и создаём таблицу слотов
CREATE TABLE EXPERT_SLOTS (
    Slot_ID         NUMBER          NOT NULL,
    Slot_Name       VARCHAR2(100)   NOT NULL,
    Slot_Desc       VARCHAR2(500)   NULL
);
ALTER TABLE EXPERT_SLOTS
    ADD CONSTRAINT C_EXPERT_SLOTS_PK PRIMARY KEY (Slot_ID);
CREATE SEQUENCE S_EXPERT_SLOTS INCREMENT BY 1 START WITH 1;

PROMPT Удаляем и создаём таблицу значений слотов
CREATE TABLE EXPERT_SLOT_VALUES (
    Slot_Value_ID   NUMBER          NOT NULL,
    Slot_ID         NUMBER          NOT NULL,
    Value_Name      VARCHAR2(200)   NOT NULL
);
ALTER TABLE EXPERT_SLOT_VALUES
    ADD CONSTRAINT C_EXPERT_SLOT_VALUES_PK PRIMARY KEY (Slot_Value_ID);
ALTER TABLE EXPERT_SLOT_VALUES
    ADD CONSTRAINT C_EXPERT_SLOT_VALUES_FK FOREIGN KEY (Slot_ID) REFERENCES EXPERT_SLOTS(Slot_ID);
CREATE SEQUENCE S_EXPERT_SLOT_VALUES INCREMENT BY 1 START WITH 1;

PROMPT Удаляем и создаём таблицу фреймов
CREATE TABLE EXPERT_FRAMES (
    Frame_ID        NUMBER          NOT NULL,
    Frame_Name      VARCHAR2(1000)   NOT NULL,
    Parent_Frame_ID NUMBER          NULL,
    Frame_Desc      VARCHAR2(1000)   NULL,
    Is_Prototype    NUMBER(1)       NOT NULL
);
ALTER TABLE EXPERT_FRAMES
    ADD CONSTRAINT C_EXPERT_FRAMES_PK PRIMARY KEY (Frame_ID);
ALTER TABLE EXPERT_FRAMES
    ADD CONSTRAINT C_EXPERT_FRAMES_SELF_FK FOREIGN KEY (Parent_Frame_ID) REFERENCES EXPERT_FRAMES(Frame_ID);
ALTER TABLE EXPERT_FRAMES
    ADD CONSTRAINT C_Is_Prototype_CHK CHECK (Is_Prototype IN (0, 1));
CREATE SEQUENCE S_EXPERT_FRAMES INCREMENT BY 1 START WITH 1;

PROMPT Удаляем и создаём таблицу связей фреймов и значений слотов
CREATE TABLE EXPERT_FRAME_VALUES (
    Frame_Value_ID  NUMBER          NOT NULL,
    Frame_ID        NUMBER          NOT NULL,
    Slot_Value_ID   NUMBER          NOT NULL
);
ALTER TABLE EXPERT_FRAME_VALUES
    ADD CONSTRAINT C_EXPERT_FRAME_VALUES_PK PRIMARY KEY (Frame_Value_ID);
ALTER TABLE EXPERT_FRAME_VALUES
    ADD CONSTRAINT C_EXPERT_FRAME_VALUES_Frame_FK FOREIGN KEY (Frame_ID) REFERENCES EXPERT_FRAMES(Frame_ID);
ALTER TABLE EXPERT_FRAME_VALUES
    ADD CONSTRAINT C_EXPERT_FRAME_VALUES_SlotVal_FK FOREIGN KEY (Slot_Value_ID) REFERENCES EXPERT_SLOT_VALUES(Slot_Value_ID);
CREATE SEQUENCE S_EXPERT_FRAME_VALUES INCREMENT BY 1 START WITH 1;

PROMPT Удаляем и создаём таблицу операций в составе техпроцесса
CREATE TABLE EXPERT_PROCESS_OPERATIONS (
    Process_Op_ID       NUMBER        NOT NULL,
    Operation_Name      VARCHAR(1000) NOT NULL,
    Frame_ID            NUMBER        NOT NULL,
    Operation_ID        NUMBER        NOT NULL,
    Op_Order            NUMBER        NOT NULL,
    Op_Duration         NUMBER        NOT NULL,
    Tool_ID             NUMBER        NULL
);
ALTER TABLE EXPERT_PROCESS_OPERATIONS
    ADD CONSTRAINT C_EXPERT_PROC_OP_PK PRIMARY KEY (Process_Op_ID);
ALTER TABLE EXPERT_PROCESS_OPERATIONS
    ADD CONSTRAINT C_EXPERT_PROC_OP_Frame_FK FOREIGN KEY (Frame_ID) REFERENCES EXPERT_FRAMES(Frame_ID);
ALTER TABLE EXPERT_PROCESS_OPERATIONS
    ADD CONSTRAINT C_EXPERT_PROC_OP_Op_FK FOREIGN KEY (Operation_ID) REFERENCES TCHG_OPERATION_LIST(Operation_ID);
ALTER TABLE EXPERT_PROCESS_OPERATIONS
    ADD CONSTRAINT C_EXPERT_PROC_OP_Tool_FK FOREIGN KEY (Tool_ID) REFERENCES TCHG_TOOLS(Tool_ID);
CREATE SEQUENCE S_EXPERT_PROCESS_OPERATIONS INCREMENT BY 1 START WITH 1;

CREATE TABLE EXPERT_SESSION (
    Answer_ID       NUMBER          NOT NULL,
    User_ID         NUMBER          NOT NULL,
    Frame_ID        NUMBER          NULL,
    Slot_ID         NUMBER          NULL,
    Slot_Value_ID   NUMBER          NULL,
    Answer          NUMBER(1)       NULL  -- 1 = да, 0 = нет
);

ALTER TABLE EXPERT_SESSION
    ADD CONSTRAINT C_EXPERT_SESSION_PK PRIMARY KEY (Answer_ID);

ALTER TABLE EXPERT_SESSION
    ADD CONSTRAINT FK_EXPERT_SESSION_USER
    FOREIGN KEY (User_ID) REFERENCES AUTH_USERS(User_ID);

ALTER TABLE EXPERT_SESSION
    ADD CONSTRAINT FK_EXPERT_SESSION_FRAME
    FOREIGN KEY (Frame_ID) REFERENCES EXPERT_FRAMES(Frame_ID);

ALTER TABLE EXPERT_SESSION
    ADD CONSTRAINT FK_EXPERT_SESSION_SLOT
    FOREIGN KEY (Slot_ID) REFERENCES EXPERT_SLOTS(Slot_ID);

ALTER TABLE EXPERT_SESSION
    ADD CONSTRAINT FK_EXPERT_SESSION_SLOT_VAL
    FOREIGN KEY (Slot_Value_ID) REFERENCES EXPERT_SLOT_VALUES(Slot_Value_ID);

CREATE SEQUENCE S_EXPERT_SESSION INCREMENT BY 1 START WITH 1;

PROMPT Создаём публичные синонимы
DROP PUBLIC SYNONYM EXPERT_SLOTS;
CREATE PUBLIC SYNONYM EXPERT_SLOTS FOR EXPERT_SLOTS;
DROP PUBLIC SYNONYM S_EXPERT_SLOTS;
CREATE PUBLIC SYNONYM S_EXPERT_SLOTS FOR S_EXPERT_SLOTS;

DROP PUBLIC SYNONYM EXPERT_SLOT_VALUES;
CREATE PUBLIC SYNONYM EXPERT_SLOT_VALUES FOR EXPERT_SLOT_VALUES;
DROP PUBLIC SYNONYM S_EXPERT_SLOT_VALUES;
CREATE PUBLIC SYNONYM S_EXPERT_SLOT_VALUES FOR S_EXPERT_SLOT_VALUES;

DROP PUBLIC SYNONYM EXPERT_FRAMES;
CREATE PUBLIC SYNONYM EXPERT_FRAMES FOR EXPERT_FRAMES;
DROP PUBLIC SYNONYM S_EXPERT_FRAMES;
CREATE PUBLIC SYNONYM S_EXPERT_FRAMES FOR S_EXPERT_FRAMES;

DROP PUBLIC SYNONYM EXPERT_FRAME_VALUES;
CREATE PUBLIC SYNONYM EXPERT_FRAME_VALUES FOR EXPERT_FRAME_VALUES;
DROP PUBLIC SYNONYM S_EXPERT_FRAME_VALUES;
CREATE PUBLIC SYNONYM S_EXPERT_FRAME_VALUES FOR S_EXPERT_FRAME_VALUES;

DROP PUBLIC SYNONYM EXPERT_PROCESS_OPERATIONS;
CREATE PUBLIC SYNONYM EXPERT_PROCESS_OPERATIONS FOR EXPERT_PROCESS_OPERATIONS;
DROP PUBLIC SYNONYM S_EXPERT_PROCESS_OPERATIONS;
CREATE PUBLIC SYNONYM S_EXPERT_PROCESS_OPERATIONS FOR S_EXPERT_PROCESS_OPERATIONS;

DROP PUBLIC SYNONYM EXPERT_SESSION;
CREATE PUBLIC SYNONYM EXPERT_SESSION FOR EXPERT_SESSION;
DROP PUBLIC SYNONYM S_EXPERT_SESSION;
CREATE PUBLIC SYNONYM S_EXPERT_SESSION FOR S_EXPERT_SESSION;
SPOOL off;
quit;
