SPOOL log_temp.txt

PROMPT Триггер для EXPERT_SLOTS
CREATE OR REPLACE TRIGGER TR_EXPERT_SLOTS_ID
    BEFORE INSERT ON EXPERT_SLOTS
    FOR EACH ROW
BEGIN
    IF :NEW.Slot_ID IS NULL THEN
        :NEW.Slot_ID := S_EXPERT_SLOTS.NEXTVAL;
    END IF;
END;
/ 

PROMPT Триггер для EXPERT_SLOT_VALUES
CREATE OR REPLACE TRIGGER TR_EXPERT_SLOT_VALUES_ID
    BEFORE INSERT ON EXPERT_SLOT_VALUES
    FOR EACH ROW
BEGIN
    IF :NEW.Slot_Value_ID IS NULL THEN
        :NEW.Slot_Value_ID := S_EXPERT_SLOT_VALUES.NEXTVAL;
    END IF;
END;
/

PROMPT Триггер для EXPERT_FRAMES
CREATE OR REPLACE TRIGGER TR_EXPERT_FRAMES_ID
    BEFORE INSERT ON EXPERT_FRAMES
    FOR EACH ROW
BEGIN
    IF :NEW.Frame_ID IS NULL THEN
        :NEW.Frame_ID := S_EXPERT_FRAMES.NEXTVAL;
    END IF;
END;
/

PROMPT Триггер для EXPERT_FRAME_VALUES
CREATE OR REPLACE TRIGGER TR_EXPERT_FRAME_VALUES_ID
    BEFORE INSERT ON EXPERT_FRAME_VALUES
    FOR EACH ROW
BEGIN
    IF :NEW.Frame_Value_ID IS NULL THEN
        :NEW.Frame_Value_ID := S_EXPERT_FRAME_VALUES.NEXTVAL;
    END IF;
END;
/

PROMPT Триггер для EXPERT_PROCESS_OPERATIONS
CREATE OR REPLACE TRIGGER TR_EXPERT_PROCESS_OPERATIONS_ID
    BEFORE INSERT ON EXPERT_PROCESS_OPERATIONS
    FOR EACH ROW
BEGIN
    IF :NEW.Process_Op_ID IS NULL THEN
        :NEW.Process_Op_ID := S_EXPERT_PROCESS_OPERATIONS.NEXTVAL;
    END IF;
END;
/

PROMPT Триггер для EXPERT_SESSION
CREATE OR REPLACE TRIGGER TR_EXPERT_SESSION_ID
    BEFORE INSERT ON EXPERT_SESSION
    FOR EACH ROW
BEGIN
    IF :NEW.Answer_ID IS NULL THEN
        :NEW.Answer_ID := S_EXPERT_SESSION.NEXTVAL;
    END IF;
END;
/

SPOOL off;
quit;
